resource_types:
  - name: docker-image
    type: registry-image
    source:
      repository: concourse/registry-image-resource

jobs:
  - name: build-and-run-dagger
    public: true
    plan:
      - task: run-dagger-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.10-alpine"
          inputs:
            - name: ruby-app-repo
          run:
            path: sh
            args:
              - -exc
              - |
                pip install dagger-io
                cd ruby-app-repo
                python dagger_build.py
