resources:
  - name: ruby-app-repo
    type: git
    source:
      uri: https://github.com/sezginerdem/ruby-hello-dagger.git
      git_config:
        - name: safe.directory
          value: /tmp/build/get

jobs:
  - name: build-and-run-dagger-dind
    plan:
      - get: ruby-app-repo
      - task: run-dagger-inside-dind
        privileged: true  # DinD için şart
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker
              tag: dind
          inputs:
            - name: ruby-app-repo
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                dockerd-entrypoint.sh &

                echo "🐳 Docker daemon başlatıldı. Bekleniyor..."
                while(! docker info > /dev/null 2>&1); do sleep 1; done

                echo "✅ Docker hazır!"
                apk add --no-cache python3 py3-pip curl
                pip install dagger-io
                cd ruby-app-repo/ruby-app-repo
                python3 dagger_build.py