jobs:
  - name: build-and-run-dagger
    public: true
    plan:
      - task: run-dagger-pipeline
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
              tag: "22.04"
          inputs:
            - name: ruby-app-repo
          run:
            path: sh
            args:
              - -exc
              - |
                apt update
                apt install -y python3 python3-pip curl gnupg
                pip3 install dagger-io
                cd ruby-app-repo
                python3 dagger_build.py
