resources:
  - name: ruby-app-repo
    type: git
    source:
      uri: https://github.com/sezginerdem/ruby-hello-dagger.git
jobs:
  - name: build-and-run-dagger
    public: true
    plan:
      - get: ruby-app-repo
      - task: run-dagger-pipeline
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.10"
          inputs:
            - name: ruby-app-repo
          run:
            path: sh
            args:
              - -exc
              - |
                pip install dagger-io
                cd ruby-app-repo/ruby-app-repo
                python dagger_build.py
