concourse:
  web:
    externalUrl: http://54.171.195.95:30080
    auth:
      localUsers: "test:test"
    mainTeam:
      localUser: "test"
    service:
      type: NodePort
      nodePort: 30080
  worker:
    runtime: "containerd"

postgresql:
  enabled: true
  auth:
    username: concourse
    password: changeme
    database: concourse
