resource_types: []

resources: []

jobs:
  - name: hello-job
    public: true
    plan:
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          run:
            path: sh
            args:
              - -c
              - echo "👋 Merhaba Dagger ve Concourse!"