resources:
  - name: ruby-hello-dagger
    type: git
    source:
      uri: file:///Users/sezginerdem/Development/ruby-hello-dagger
      branch: main
jobs:
  - name: dagger-build
    plan:
      - task: dagger-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11-bullseye"
          inputs:
            - name: ruby-hello-dagger
          run:
            path: ruby-hello-dagger/concourse/task-scripts/dagger-task.sh
