resources:
  - name: ruby-hello-dagger
    type: git
    source:
      uri: https://github.com/sezginerdem/ruby-hello-dagger.git
      branch: main
      git_config:
        - name: safe.directory
          value: /tmp/build/get

jobs:
  - name: run-dagger-task
    plan:
      - task: dagger-example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: python, tag: "3.11" }
          inputs:
            - name: dagger
          run:
            path: python
            args:
              - dagger/dagger_build.py
